### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by joanafbrito** [joanafbrito/tomates-podres#15]
As a user, in order to find a movie in the home page from a search bar, after typing the movie title when ? I click the search button, then I should see the movie selected .

Acceptance Criteria:

  - [x] Have Search Input
  - [x] Search button click selects single movie and redisplays the movie poster
  - [x] Search Input updates from  each letter to the show the movies ?

**Comment by Meggs625** [comment]
All acceptance criteria pass for this issue
